

  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kubernetes-cluster-rohitsharma04
  spec:
    replicas: 4
    selector:
      matchLabels:
        app: kubernetes-cluster-rohitsharma04
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: rohit2522/nagp-jenkins-assignment:latest
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
          
  apiVersion: apps/v1
  kind: Service
  metadata:
    name: kubernetes-cluster-rohitsharma04
  spec:
    type: NodePort
    selector:
        app: kubernetes-cluster-rohitsharma04
    ports:
        - protocol: TCP
          nodePort: 30158
          port: 80
          targetPort: 80
  
          