  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kubernetes-deployment-master
    labels:
      app: kubernetes-app-master
    
  spec:
    replicas: 4
    selector:
      matchLabels:
        app: kubernetes-app-master
  template:
    metadata:
      labels:
        app: kubernetes-app-master
    spec:
      containers:
      - name: kubernetes-deployment-master
        image: rohit2522/nagp-jenkins-assignment:master-latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
          
  apiVersion: apps/v1
  kind: Service
  metadata:
    name: kubernetes-deployment-master
  spec:
    type: NodePort
    selector:
        app: kubernetes-app-master
    ports:
        - protocol: TCP
          nodePort: 30157
          port: 8080
          targetPort: 8080
  
          